### ISSUE TITLE
Polymorphic associations are not being used right

### ISSUE THREAD

**Issue by heyapricot** [dipto0321/facialbook#6]
You define three polymorphic associations: commentable, postable and likable. Yet, you only have one model that uses comments, one model that uses posts and one model that uses likes. So, what's the point?

**Comment by rvvergara** [comment]
Hi @heyapricot,

Thanks for raising this issue. 

I'm not sure if I follow what you mean, though. We do allow commenting on [comments](https://github.com/dipto0321/facialbook/blob/63991a210ef02339fffae90d789e313cb2eb1d0a/app/models/comment.rb#L6) themselves. As well as liking both [posts](https://github.com/dipto0321/facialbook/blob/63991a210ef02339fffae90d789e313cb2eb1d0a/app/models/post.rb#L7) and [comments](https://github.com/dipto0321/facialbook/blob/63991a210ef02339fffae90d789e313cb2eb1d0a/app/models/comment.rb#L7). We made `post` polymorphic for extensibility purposes (we intend to extend the app to have Pages and Groups which will also be postables).

**Comment by rvvergara** [comment]
@heyapricot, I am closing this issue as no response coming from your part and we believe we have clarified it.
